name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check VPS_HOST variable
        run: echo "VPS_HOST is: $VPS_HOST"
        env:
          VPS_HOST: ${{ vars.VPS_HOST }}

      - name: Check SSH private key
        run: |
          echo "SSH key starts with: $(echo "$SSH_PRIVATE_KEY" | head -c 10)..."
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa -p 5026 "$VPS_HOST" > ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_HOST: ${{ vars.VPS_HOST }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ vars.VPS_HOST }}
          username: root
          port: 5026
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/admin-jpmb/
            git pull origin main
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
